[17-Feb-2017 16:18:53] #### UPDATE TO v5.000 STARTED
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/ext/modules/payment/paypal/express.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/actions/balance/retrieve.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/actions/credentials/process.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/actions/credentials.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/actions/start/process.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/actions/start/retrieve.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/content/credentials.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/content/privacy.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/admin/content/start.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/api/BMCreateButton.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/hooks/admin/orders/tab.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/admin/credentials.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/admin/privacy.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/modules/EC/cfg_params/checkout_flow.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_color.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_shape.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_size.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/languages/english/modules/LOGIN/LOGIN.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/DP/api/DoDirectPayment.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/DP/api/PayflowPayment.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/DP/DP.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/api/DoExpressCheckoutPayment.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/api/PayflowDoExpressCheckoutPayment.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/cfg_params/checkout_flow.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/cfg_params/incontext_button_color.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/cfg_params/incontext_button_shape.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/cfg_params/incontext_button_size.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/cfg_params/transaction_method.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/EC/EC.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/HS/HS.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/LOGIN/api/UserInfo.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/LOGIN/LOGIN.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/modules/PS/cfg_params/prepare_order_status_id.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/OSCOM_PayPal.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/version.txt
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/modules/payment/paypal_express.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/modules/payment/paypal_standard.php
[17-Feb-2017 16:18:53] Updated: /var/www/vhosts/webdesign-wedel.de/httpdocs/osc.webdesign-wedel.de/includes/apps/paypal/version.txt
[17-Feb-2017 16:18:53] #### UPDATE TO v5.000 COMPLETED
